reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
